<a href="https://colab.research.google.com/github/Debo12/ddutta.guvi-proj/blob/master/assignments/Numpy_tasks_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [212]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [213]:
np.__version__

'1.21.6'

In [214]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [215]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [216]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [217]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [218]:
arr = np.zeros(10, dtype=int)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [219]:
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [220]:
arr = np.arange(10, 49)
arr[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [221]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [222]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [223]:
np.eye(3, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [224]:
np.random.random([3, 3, 3])

array([[[0.87875285, 0.37101903, 0.25061039],
        [0.28140449, 0.70537888, 0.44799571],
        [0.48096291, 0.81829896, 0.54410872]],

       [[0.72806118, 0.04669895, 0.59179774],
        [0.46394953, 0.49663447, 0.50194437],
        [0.89327815, 0.93217621, 0.26121436]],

       [[0.82372365, 0.02548257, 0.45309352],
        [0.12852735, 0.77725577, 0.21358963],
        [0.51610067, 0.70688535, 0.77267013]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [225]:
arr = np.random.random([10, 10])

In [226]:
arr

array([[0.69048364, 0.83453809, 0.04416355, 0.28437543, 0.56684114, 0.0137021 , 0.77032046, 0.96196182, 0.57467953, 0.21334986],
       [0.88482089, 0.46953541, 0.62585758, 0.32123976, 0.7757713 , 0.91753125, 0.04736128, 0.53319826, 0.13149111, 0.09693665],
       [0.97781932, 0.71613547, 0.82803832, 0.79662741, 0.60240838, 0.81262404, 0.45910706, 0.75435413, 0.40215319, 0.44070751],
       [0.6360938 , 0.87084661, 0.52136128, 0.52884946, 0.43493524, 0.32842071, 0.33173166, 0.60417545, 0.70649826, 0.78380913],
       [0.55710862, 0.12509523, 0.96425469, 0.6570938 , 0.35492597, 0.57482932, 0.66815812, 0.84020499, 0.42739896, 0.6147774 ],
       [0.75413352, 0.50319043, 0.35471659, 0.57273055, 0.23850415, 0.01883415, 0.82059261, 0.04347432, 0.23026578, 0.71227563],
       [0.44065553, 0.25374577, 0.0556275 , 0.92691608, 0.82782462, 0.47418738, 0.37501355, 0.9166262 , 0.1549409 , 0.15123809],
       [0.5470318 , 0.90175976, 0.42631617, 0.05993067, 0.89862726, 0.73027818, 0.45773455, 0.157

In [227]:
np.max(arr)

0.9778193228746785

In [228]:
np.min(arr)

0.013702095815957382

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [229]:
arr = np.random.random(30)
np.mean(arr)

0.4449795285970659

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [230]:
arr = np.ones([5, 5])
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [231]:
arr = np.ones([5, 5])
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan :: nan
np.nan == np.nan : False
np.inf > np.nan :: False
np.nan - np.nan :: nan
0.3 == 3 * 0.1 :: False
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [232]:
print(np.diag([1, 2, 3, 4], k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [233]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [234]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [235]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [236]:
z=np.random.random([5,5])
z=(z-np.min(z))/(np.max(z) - np.min(z))
print(z)

[[0.44944235 0.86118064 0.         0.99317904 0.89138649]
 [0.32747643 0.23764213 1.         0.44286116 0.99753708]
 [0.12203885 0.26674358 0.14872776 0.14582051 0.17467386]
 [0.2913609  0.88636577 0.35922303 0.94717153 0.88175401]
 [0.52174697 0.88682807 0.38718062 0.15314386 0.33204019]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [237]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])

1


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [238]:
z=np.dot(np.random.rand(5,3),np.random.rand(3,2))
print(z)

[[1.09141251 0.69375373]
 [0.63981965 0.50400043]
 [1.01642834 0.628897  ]
 [1.32576226 0.95139582]
 [0.7730927  0.56474996]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [239]:
arr = np.arange(16)
arr[(arr>=3) & (arr<=8)]*=(-1)
print(arr)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Following expressions are legal -

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan

0

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [240]:
arr = np.random.random((5,5))
arr = np.round(arr,2)
print(arr)

[[0.05 0.31 0.87 0.89 0.37]
 [0.12 0.14 0.35 0.16 0.56]
 [0.56 0.39 0.18 0.69 0.97]
 [0.58 0.25 0.65 0.07 0.51]
 [0.44 0.89 0.   0.5  0.68]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [241]:
arr_1 = np.arange(9).reshape(3,3)
arr_2 = np.array([[0,1,2],[3,4,5],[17,18,19]])
np.intersect1d(arr_1, arr_2)

array([0, 1, 2, 3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [242]:
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0
x

array([inf])

In [243]:
with np.errstate(divide='ignore'):
    x = np.ones(1) / 0
    print(x)

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [244]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [245]:
print(np.datetime64('today', 'D')) #Today date

2023-01-03


In [246]:
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D')) # Yesterday date

2023-01-02


In [247]:
print(np.datetime64('today', 'D') + np.timedelta64(1, 'D')) # Tomorrow date

2023-01-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [248]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05' '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10' '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15' '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20' '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25' '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30' '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [249]:
A = np.ones(3)*1
B = np.ones(3)*2

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [250]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print(np.trunc(Z))

[6. 0. 5. 9. 8. 7. 6. 6. 5. 5.]
[6. 0. 5. 9. 8. 7. 6. 6. 5. 5.]
[6. 0. 5. 9. 8. 7. 6. 6. 5. 5.]
[6 0 5 9 8 7 6 6 5 5]
[6. 0. 5. 9. 8. 7. 6. 6. 5. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [251]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [252]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [253]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [254]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.11657012 0.15231323 0.15656792 0.25642949 0.26935306 0.33069131 0.60289724 0.63025758 0.84287931 0.87995484]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [255]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [256]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [257]:
A

array([1, 1, 1, 0, 1])

In [258]:
B

array([1, 0, 0, 0, 0])

In [259]:
print(np.allclose(A,B))

False


In [260]:
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [261]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [262]:
z= np.random.randint(0,9,(10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[ 5.          0.92729522]
 [ 6.70820393  1.10714872]
 [ 4.12310563  1.32581766]
 [ 5.          0.92729522]
 [ 1.          0.        ]
 [ 7.28010989  1.29249667]
 [ 8.24621125  0.24497866]
 [ 4.47213595  1.10714872]
 [11.3137085   0.78539816]
 [ 7.81024968  0.87605805]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [263]:
arr = np.random.random(10)
print(arr)
print('*'*60)
arr[arr.argmax()] = 0
print(arr)

[0.43792261 0.2309609  0.31621581 0.43645991 0.70364406 0.20591277 0.42544374 0.0620684  0.2098865  0.69189441]
************************************************************
[0.43792261 0.2309609  0.31621581 0.43645991 0.         0.20591277 0.42544374 0.0620684  0.2098865  0.69189441]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [264]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        ) (0.22222222, 0.        ) (0.33333333, 0.        ) (0.44444444, 0.        ) (0.55555556, 0.        ) (0.66666667, 0.        ) (0.77777778, 0.        ) (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111) (0.22222222, 0.11111111) (0.33333333, 0.11111111) (0.44444444, 0.11111111) (0.55555556, 0.11111111) (0.66666667, 0.11111111) (0.77777778, 0.11111111) (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222) (0.22222222, 0.22222222) (0.33333333, 0.22222222) (0.44444444, 0.22222222) (0.55555556, 0.22222222) (0.66666667, 0.22222222) (0.77777778, 0.22222222) (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333) (0.22222222, 0.33333333) (0.33333333, 0.33333333) (0.44444444, 0.33333333) (0.55555556, 0.33333333) (0.66666667, 0.33333333) (0.77777778, 0.33333333) (0.88888889, 0.33333333) (1.        , 0

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [265]:
Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
Y = np.tile(Y,(10,1))
X  = np.tile(X,(10,1)).T

C = 1.0/np.subtract.outer(x, y), 1.0/(x[:,None]-y)
C

(array([[-1.        , -0.33333333, -1.        , -1.        ,  0.33333333, -0.25      ,  1.        , -1.        , -0.2       , -0.33333333],
        [-1.        , -0.33333333, -1.        , -1.        ,  0.33333333, -0.25      ,  1.        , -1.        , -0.2       , -0.33333333],
        [-0.33333333, -0.2       , -0.33333333, -0.33333333,  1.        , -0.16666667, -1.        , -0.33333333, -0.14285714, -0.2       ],
        [-1.        , -0.33333333, -1.        , -1.        ,  0.33333333, -0.25      ,  1.        , -1.        , -0.2       , -0.33333333],
        [-0.33333333, -0.2       , -0.33333333, -0.33333333,  1.        , -0.16666667, -1.        , -0.33333333, -0.14285714, -0.2       ],
        [-0.5       , -0.25      , -0.5       , -0.5       ,  0.5       , -0.2       ,         inf, -0.5       , -0.16666667, -0.25      ],
        [ 0.25      ,  0.5       ,  0.25      ,  0.25      ,  0.125     ,  1.        ,  0.16666667,  0.25      ,         inf,  0.5       ],
        [-0.5       

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [266]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [267]:
np.set_printoptions(threshold=np.inf, linewidth=np.nan)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [268]:
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[2.98327277 4.58242461 1.59287592 1.98238693 5.81619874 9.3451175  1.38646475 7.07357902 5.67472783 1.90876264]
************************************************************
4.582424609821098


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [269]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [270]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.41598685 0.43697734 0.87243619 0.88116443 0.55852841 0.8213325  0.21977335 0.35067283 0.21741337 0.51428606 0.42353919 0.99106906 0.24792191 0.49004894 0.84682691 0.28038745 0.72027954 0.84891276 0.5850367  0.98545601 0.55194411 0.20451135 0.83315863 0.46555351 0.53734093 0.42555315 0.54965397 0.74510963 0.52483072 0.56612152 0.68042843 0.74471334 0.41979303 0.55602792 0.64795317 0.54488467 0.29434296 0.56152662 0.81211314 0.49887276 0.9724433  0.54200828 0.42470728 0.09202702 0.66219091 0.38486997 0.70171631 0.0991324  0.70751422 0.36252127 0.1842833  0.52923042 0.04264961 0.83244731 0.7427272  0.48793392 0.82973668 0.51655706 0.81974553 0.15905741 0.27260865 0.92544224 0.25936784 0.3472301  0.51601991 0.72005073 0.27738962 0.04132289 0.67326299 0.42612728 0.36769829 0.56761614 0.72768837 0.5940259  0.44379328 0.38835475 0.26994725 0.6122604  0.74700971 0.89732346 0.45567343 0.09977796 0.44261819 0.40693805 0.71931158 0.5527519  0.73196647 0.55635991 0.4954254  0.397330

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [271]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [272]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [273]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [274]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818 0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.5461

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [275]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [276]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [277]:
Z = np.random.randint(0,10,(5,5))
print(Z)

[[4 0 0 5 2]
 [4 3 3 3 0]
 [2 5 5 1 3]
 [6 5 7 5 5]
 [7 6 2 6 3]]


In [278]:
print(Z[(-Z)[:,1].argsort()])

[[7 6 2 6 3]
 [2 5 5 1 3]
 [6 5 7 5 5]
 [4 3 3 3 0]
 [4 0 0 5 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [279]:
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
print(Z)

[[1 0 1 0 0 1 1 1 2 2]
 [2 0 1 2 1 1 2 0 2 1]
 [0 0 2 1 0 2 1 1 1 1]]


In [280]:
Z = Z.astype(bool)
print(Z)

[[ True False  True False False  True  True  True  True  True]
 [ True False  True  True  True  True  True False  True  True]
 [False False  True  True False  True  True  True  True  True]]


In [281]:
print(~Z)

[[False  True False  True  True False False False False False]
 [False  True False False False False False  True False False]
 [ True  True False False  True False False False False False]]


In [282]:
print((Z).any(axis = 0))

[ True False  True  True  True  True  True  True  True  True]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [283]:
x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

5.022172736522722


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [284]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [285]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [286]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 5. 2. 4. 4. 1. 3. 3. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [287]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [288]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [289]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[53 57 74 50]
 [59 58 60 44]
 [67 54 66 46]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [290]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.38967754 0.52621866 0.52514317 0.4707703  0.65877993 0.42775591 0.45888868 0.42315462 0.49248049 0.53711998]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [291]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

print(np.diag(np.dot(A, B)))

[0.66283978 1.09241552 0.32347999 1.15763321 2.12272322]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [292]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [293]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [294]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [295]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 62) ( 4, 99) ( 6, 36) ( 6, 52) (14, 16) (14, 63) (16, 26) (16, 52) (16, 59) (16, 63) (16, 91) (17, 91) (17, 96) (26, 52) (36, 52) (43, 56) (43, 73) (48, 74) (48, 91) (53, 67) (53, 79) (55, 70) (55, 99) (56, 73) (59, 91) (62, 99) (67, 79) (70, 99) (74, 91) (91, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [296]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [297]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [298]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [299]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0])

In [300]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-4.86942010e-02, -6.28048367e-01, -9.72527312e-01,  1.63183741e-01, -4.93081696e-01,  6.00382378e-01, -5.34596883e-01,  7.26749010e-01,  5.80639830e-01, -6.72141721e-01, -1.38459783e-01, -9.68325672e-01,  5.06184313e-01, -1.99473780e-01,  4.70263947e-02, -1.82024960e-01, -7.26568356e-01, -9.26557520e-01, -9.92478888e-01,  8.39636866e-01,  2.25417128e-01,  5.56583695e-02, -3.58282058e-01,  4.04517751e-01, -5.86511696e-01, -8.94171714e-01, -8.32044213e-01,  4.10073552e-01,  7.58969866e-01, -2.10060961e-01,  8.26807136e-01, -5.63706162e-01,  7.09856687e-01,  3.69468972e-01, -3.66937375e-01, -6.62457145e-01,  7.95444697e-01, -4.47158581e-01,  3.92678957e-01,  4.56315818e-01, -5.86246875e-01, -6.01363417e-02,  6.29286541e-04,  2.93086914e-02, -5.89731348e-01,  3.28396972e-01, -6.01845439e-01,  3.34784801e-01,  9.31118392e-01,  7.15202797e-01,  4.44512678e-01,  6.56970271e-01, -7.96176110e-01, -6.50593524e-01, -7.08206373e-01, -2.55907794e-01,  8.15790760e-01,  4.52687416e-01,  1.6132

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [301]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.92241231 0.9033534  1.97828907 2.00597985 2.55865713 0.54570334 1.25799145 2.8449429  5.9822501  7.14141493]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [302]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[13.88508381  5.67268111 17.34039856  0.08067335  9.90356851  6.80048694 13.33309431  1.12658604  8.96998444  2.88349648]
 [ 5.29292008 13.53196566  0.99656077 14.75447149  9.3116594  12.07701098  1.85643856 15.02952562  7.50901956 14.90173185]
 [12.36312015  4.32846424 15.46366567  2.3027038   8.46380134  5.0824911  11.06858456  0.90056118  6.8480929   2.38239613]
 [ 5.45797948  3.51986657 11.04928328  2.09686075  1.1032707   0.57312815 13.96306853 10.39849542  5.14055782 14.26133088]
 [ 1.58047029  7.52123472  7.61946682  4.36711173  2.8378522   4.24504725 12.5343382  14.36067606  2.34499665 17.64954137]
 [ 4.55141802 12.38711068  1.23044236 16.55263643  8.37824886 11.8389674   0.72790596 12.04247432  8.69293836 11.18273703]
 [ 0.46644801  8.03938417  2.07289835 14.93862318  4.1636415   8.13228814  0.21826745  7.09162635  6.34651174  6.5433308 ]
 [ 2.43566053  5.53403277  5.7870064  10.36161643  1.44564308  4.78568922  4.53497069  7.00018635  2.03870597  7.96658478]
 [ 3.26576342  6

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [303]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 1 2 7 2 2 8 1 9 9]
 [8 2 4 7 7 1 8 8 6 2]
 [4 2 6 9 3 2 5 6 9 0]
 [5 6 3 4 5 1 1 3 5 4]
 [0 5 6 1 8 0 1 5 7 1]
 [7 0 0 9 0 3 6 2 3 0]
 [2 8 0 7 5 1 5 8 4 7]
 [9 5 4 5 1 3 5 6 6 0]
 [9 2 9 2 1 6 3 5 5 4]
 [4 7 8 1 6 9 9 4 1 5]]
[[0 0 0 0 0]
 [0 5 1 2 7]
 [0 8 2 4 7]
 [0 4 2 6 9]
 [0 5 6 3 4]]


<ipython-input-303-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [304]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [305]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [306]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [307]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 4 1]
   [4 3 0]
   [1 2 1]]

  [[4 1 1]
   [3 0 2]
   [2 1 0]]

  [[1 1 0]
   [0 2 2]
   [1 0 3]]

  [[1 0 0]
   [2 2 2]
   [0 3 2]]

  [[0 0 0]
   [2 2 0]
   [3 2 3]]

  [[0 0 4]
   [2 0 3]
   [2 3 3]]

  [[0 4 0]
   [0 3 1]
   [3 3 0]]

  [[4 0 3]
   [3 1 0]
   [3 0 0]]]


 [[[4 3 0]
   [1 2 1]
   [3 0 2]]

  [[3 0 2]
   [2 1 0]
   [0 2 0]]

  [[0 2 2]
   [1 0 3]
   [2 0 1]]

  [[2 2 2]
   [0 3 2]
   [0 1 3]]

  [[2 2 0]
   [3 2 3]
   [1 3 3]]

  [[2 0 3]
   [2 3 3]
   [3 3 4]]

  [[0 3 1]
   [3 3 0]
   [3 4 1]]

  [[3 1 0]
   [3 0 0]
   [4 1 2]]]


 [[[1 2 1]
   [3 0 2]
   [4 4 1]]

  [[2 1 0]
   [0 2 0]
   [4 1 4]]

  [[1 0 3]
   [2 0 1]
   [1 4 4]]

  [[0 3 2]
   [0 1 3]
   [4 4 3]]

  [[3 2 3]
   [1 3 3]
   [4 3 0]]

  [[2 3 3]
   [3 3 4]
   [3 0 3]]

  [[3 3 0]
   [3 4 1]
   [0 3 0]]

  [[3 0 0]
   [4 1 2]
   [3 0 3]]]


 [[[3 0 2]
   [4 4 1]
   [0 0 2]]

  [[0 2 0]
   [4 1 4]
   [0 2 4]]

  [[2 0 1]
   [1 4 4]
   [2 4 0]]

  [[0 1 3]
   [4 4 3]
   [4 0 4]]

  [[1 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [308]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  3 16  7  8]
 [ 3  2 10 12  4]
 [16 10  0 42 16]
 [ 7 12 42  9 11]
 [ 8  4 16 11  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [309]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [310]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [311]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [312]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [313]:
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [314]:
print (Z[np.argpartition(-Z,n)[:n]])

[9996 9997 9999 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [315]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [316]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [317]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.85 s ± 49.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
158 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
125 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [318]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [319]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[1 4 3]
 [1 4 3]
 [0 1 1]
 [3 0 4]
 [4 2 2]
 [0 3 0]
 [0 1 0]
 [1 2 1]
 [1 0 3]
 [2 3 2]]
[[1 4 3]
 [1 4 3]
 [0 1 1]
 [3 0 4]
 [4 2 2]
 [0 3 0]
 [0 1 0]
 [1 2 1]
 [1 0 3]
 [2 3 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [320]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [321]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [322]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)

4.811840067168879

In [323]:
np.einsum('i,i->i', A, B)

array([0.13729581, 0.23724738, 0.13592123, 0.29974607, 0.00351218, 0.1123692 , 0.40283433, 0.3014847 , 0.33966564, 0.31753738])

In [324]:
np.einsum('i,i', A, B)

2.2876139226650736

In [325]:
np.einsum('i,j->ij', A, B) 

array([[0.13729581, 0.44183036, 0.21325447, 0.44468874, 0.0221898 , 0.11694987, 0.57803541, 0.43897424, 0.33201073, 0.25287559],
       [0.07372303, 0.23724738, 0.11451016, 0.23878223, 0.01191514, 0.06279797, 0.3103847 , 0.23571374, 0.1782781 , 0.13578531],
       [0.08750773, 0.28160781, 0.13592123, 0.28342964, 0.01414303, 0.07453991, 0.36842032, 0.27978741, 0.21161247, 0.1611744 ],
       [0.09254536, 0.29781936, 0.14374592, 0.29974607, 0.01495722, 0.07883101, 0.38962948, 0.29589417, 0.22379454, 0.17045286],
       [0.02173103, 0.06993243, 0.03375369, 0.07038485, 0.00351218, 0.0185107 , 0.09149082, 0.06948037, 0.0525503 , 0.04002488],
       [0.13191824, 0.42452484, 0.20490176, 0.42727126, 0.02132068, 0.1123692 , 0.55539503, 0.42178058, 0.3190066 , 0.24297101],
       [0.0956818 , 0.30791269, 0.14861758, 0.30990471, 0.01546413, 0.08150266, 0.40283433, 0.30592225, 0.23137912, 0.17622964],
       [0.09429389, 0.30344627, 0.14646181, 0.30540938, 0.01523981, 0.08032042, 0.39699102, 0.301

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [326]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [327]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [328]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.14923069  0.20631485]
